import mock from "../mock"

export const data = [
  {
    id: 157,
    offer_date: "2022-12-18",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description:
      "222222222222222222222222222222222222222222222222222222222222222222",
    train_type: "Remote",
    train_start_date: "2023-01-18",
    train_end_date: "2023-04-12",
    support_amount: "111111",
    University_id_des: 1152,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 45,
    daily_hours: 11,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "starter",
    stu_sex: "male",
    work_field: "null",
    meals_text: "Yes there is",
    residence_text: "Transfer Details",
    transfer_text: "",
    status: 6,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 111,
    inst_name: "",
    place_of_work: "",
    receive_date: "2023-01-15"
  },
  {
    id: 158,
    offer_date: "2022-12-19",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "222222222222222222222222222222222222222222222222222222222222222222",
    train_type: "Remote",
    train_start_date: "2023-01-14",
    train_end_date: "2023-01-31",
    support_amount: "111111",
    University_id_des: 2,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 45,
    daily_hours: 11,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 2,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 159,
    offer_date: "2022-12-20",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "222222222222222222222222222222222222222222222222222222222222222222",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "111111",
    University_id_des: 2,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 45,
    daily_hours: 11,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 2,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 160,
    offer_date: "2022-12-20",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "222222222222222222222222222222222222222222222222222222222222222222",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "111111",
    University_id_des: 1153,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 45,
    daily_hours: 11,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 2,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 172,
    offer_date: "2022-12-25",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-26",
    train_end_date: "2022-12-28",
    support_amount: "10101010",
    University_id_des: 2,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Undergraduate",
    stu_sex: "Female",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 2,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 177,
    offer_date: "2022-12-25",
    university_id_src: 1,
    other_requirments: "",
    train_description: "kjdjksljsls33jhjdhkjhfkjhdskjfdhhjfd",
    train_type: "Remote",
    train_start_date: "2022-12-26",
    train_end_date: "2022-12-28",
    support_amount: "101001010",
    University_id_des: 5,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 2,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 100,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 178,
    offer_date: "2022-12-25",
    university_id_src: 1,
    other_requirments: "",
    train_description: "kjdjksljsls33jhjdhkjhfkjhdskjfdhhjfd",
    train_type: "Remote",
    train_start_date: "2022-12-26",
    train_end_date: "2022-12-28",
    support_amount: "101001010",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 100,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 179,
    offer_date: "2022-12-25",
    university_id_src: 1,
    other_requirments: "",
    train_description: "kjdjksljsls33jhjdhkjhfkjhdskjfdhhjfd",
    train_type: "Remote",
    train_start_date: "2022-12-26",
    train_end_date: "2022-12-28",
    support_amount: "101001010",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 100,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 183,
    offer_date: "2022-12-25",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-27",
    train_end_date: "2022-12-28",
    support_amount: "888",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 8989,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 185,
    offer_date: "2022-12-25",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-26",
    train_end_date: "2022-12-27",
    support_amount: "1000",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 888,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 186,
    offer_date: "2022-12-26",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-27",
    train_end_date: "2022-12-28",
    support_amount: "111",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 11,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 187,
    offer_date: "2022-12-26",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-28",
    train_end_date: "2023-01-07",
    support_amount: "111",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 99,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 189,
    offer_date: "2022-12-26",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-27",
    train_end_date: "2022-12-30",
    support_amount: "33",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 33,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 190,
    offer_date: "2022-12-26",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "2022-12-27",
    train_end_date: "2022-12-30",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 192,
    offer_date: "2023-01-01",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 193,
    offer_date: "2023-01-01",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 194,
    offer_date: "2023-01-01",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 195,
    offer_date: "2023-01-01",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 196,
    offer_date: "2023-01-01",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 197,
    offer_date: "2023-01-02",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: null,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 198,
    offer_date: "2023-01-02",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "null",
    train_length: 0,
    inst_name: "Company Name",
    place_of_work: "Remote",
    receive_date: null
  },
  {
    id: 199,
    offer_date: "2023-01-02",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Field",
    train_start_date: "2023-01-14",
    train_end_date: "2024-01-01",
    support_amount: "1500",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "Computer Software",
    days_of_work: "Sun,Mon,Wed",
    weekly_hours: 35,
    daily_hours: 5,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "50",
    residence_text: "more to describe",
    transfer_text: "Daily transports",
    status: 0,
    inst_address: "Nablus / Palestine",
    inst_fax: "0945704354",
    inst_phone: "0945704354",
    trainer_name: "Eng. Tamer Naana",
    train_length: 14,
    inst_name: "Company Name",
    place_of_work: "Remote",
    receive_date: null
  },
  {
    id: 200,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "kjdjksljsls33jhjdhkjhfkjhdskjfdhhjfd",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "101001010",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "Nablus/City",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 100,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 201,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "kjdjksljsls33jhjdhkjhfkjhdskjfdhhjfd",
    train_type: "Remote",
    train_start_date: null,
    train_end_date: null,
    support_amount: "101001010",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "Nablus/City",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 100,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 202,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "kjdjksljsls33jhjdhkjhfkjhdskjfdhhjfd",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "101001010",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "xxxxxxxxxxxxxxx",
    major_name: "هندسه انظمه حاسوب",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 0,
    inst_address: "Nablus/City",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 100,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 203,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "null",
    train_length: 0,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 204,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "null",
    train_length: 0,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 205,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 0,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 206,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 0,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 207,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "",
    train_description:
      "تدريب فرونت انند داخل الشركه ومن اللممكن يتحول ل اون لاين",
    train_type: "Remote",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "108",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "",
    days_of_work: "",
    weekly_hours: 0,
    daily_hours: 0,
    college_name: "الهندسه والتكنولوحيا ",
    branch_name: "sdadsadsdsa",
    major_name: "Computer Systems Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "",
    residence_text: "",
    transfer_text: "",
    status: 1,
    inst_address: "",
    inst_fax: "",
    inst_phone: "",
    trainer_name: "",
    train_length: 0,
    inst_name: "",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 208,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Field",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "1500",
    University_id_des: 4,
    organization_id: null,
    user_id: 1,
    train_aria: "Computer Software",
    days_of_work: "Sun,Mon,Wed",
    weekly_hours: 35,
    daily_hours: 5,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "50",
    residence_text: "more to describe",
    transfer_text: "Daily transports",
    status: 2,
    inst_address: "Nablus / Palestine",
    inst_fax: "0945704354",
    inst_phone: "0945704354",
    trainer_name: "Eng. Tamer Naana",
    train_length: 14,
    inst_name: "Company Name",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 209,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Field",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "1500",
    University_id_des: 1152,
    organization_id: null,
    user_id: 1,
    train_aria: "Computer Software",
    days_of_work: "Sun,Mon,Wed",
    weekly_hours: 35,
    daily_hours: 5,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "50",
    residence_text: "more to describe",
    transfer_text: "Daily transports",
    status: 2,
    inst_address: "Nablus / Palestine",
    inst_fax: "0945704354",
    inst_phone: "0945704354",
    trainer_name: "Eng. Tamer Naana",
    train_length: 14,
    inst_name: "Company Name",
    place_of_work: "",
    receive_date: "2023-01-18"
  },
  {
    id: 210,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Field",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "1500",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "Computer Software",
    days_of_work: "Sun,Mon,Wed",
    weekly_hours: 35,
    daily_hours: 5,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "50",
    residence_text: "more to describe",
    transfer_text: "Daily transports",
    status: 0,
    inst_address: "Nablus / Palestine",
    inst_fax: "0945704354",
    inst_phone: "0945704354",
    trainer_name: "Eng. Tamer Naana",
    train_length: 14,
    inst_name: "Company Name",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 211,
    offer_date: "2023-01-13",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Field",
    train_start_date: "2023-01-20",
    train_end_date: "2023-01-27",
    support_amount: "1500",
    University_id_des: 1152,
    organization_id: null,
    user_id: 1,
    train_aria: "Computer Software",
    days_of_work: "Sun,Mon,Wed",
    weekly_hours: 35,
    daily_hours: 5,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "50",
    residence_text: "more to describe",
    transfer_text: "Daily transports",
    status: 3,
    inst_address: "Nablus / Palestine",
    inst_fax: "0945704354",
    inst_phone: "0945704354",
    trainer_name: "Eng. Tamer Naana",
    train_length: 14,
    inst_name: "Company Name",
    place_of_work: "Remote",
    receive_date: null
  },
  {
    id: 212,
    offer_date: "2023-01-14",
    university_id_src: 1,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Field",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "1500",
    University_id_des: null,
    organization_id: null,
    user_id: 1,
    train_aria: "Computer Software",
    days_of_work: "Sun,Mon,Wed",
    weekly_hours: 35,
    daily_hours: 5,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Undergraduate",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "50 more to describe",
    residence_text: "Daily transports",
    transfer_text: "null",
    status: 0,
    inst_address: "Nablus / Palestine",
    inst_fax: "0945704354",
    inst_phone: "0945704354",
    trainer_name: "Eng. Tamer Naana",
    train_length: 14,
    inst_name: "Company Name",
    place_of_work: "",
    receive_date: null
  },
  {
    id: 213,
    offer_date: "2023-01-14",
    university_id_src: 1152,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Site",
    train_start_date: "2023-01-17",
    train_end_date: "2023-08-16",
    support_amount: "150",
    University_id_des: 4,
    organization_id: null,
    user_id: null,
    train_aria: null,
    days_of_work: "Sun,Tue",
    weekly_hours: 40,
    daily_hours: 8,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 1,
    inst_address: "Izbat Salman",
    inst_fax: "0945704354",
    inst_phone: "0594360110",
    trainer_name: "Trainer Name",
    train_length: 14,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "Remote",
    receive_date: null
  },
  {
    id: 214,
    offer_date: "2023-01-11",
    university_id_src: 1152,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Site",
    train_start_date: "2023-01-20",
    train_end_date: "2023-02-23",
    support_amount: "150",
    University_id_des: 1,
    organization_id: null,
    user_id: null,
    train_aria: null,
    days_of_work: "Sun,Tue",
    weekly_hours: 40,
    daily_hours: 8,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "150 more to describe",
    residence_text: "Daily transports",
    transfer_text: "7",
    status: 0,
    inst_address: "Izbat Salman",
    inst_fax: "0945704354",
    inst_phone: "0594360110",
    trainer_name: "Trainer Name",
    train_length: 14,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "On-Site",
    receive_date: null
  },
  {
    id: 215,
    offer_date: "2023-01-13",
    university_id_src: 1152,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Site",
    train_start_date: "2023-01-24",
    train_end_date: "2023-06-23",
    support_amount: "1500",
    University_id_des: 4,
    organization_id: null,
    user_id: null,
    train_aria: null,
    days_of_work: "Sun,Tue",
    weekly_hours: 40,
    daily_hours: 8,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "150 more to describe",
    residence_text: "Daily transports",
    transfer_text: "1",
    status: 0,
    inst_address: "Izbat Salman",
    inst_fax: "0945704354",
    inst_phone: "0594360110",
    trainer_name: "Trainer Name",
    train_length: 14,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "Remote",
    receive_date: "2023-01-16"
  },
  {
    id: 216,
    offer_date: "2023-01-14",
    university_id_src: 1152,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "On-Site",
    train_start_date: "0000-00-00",
    train_end_date: "0000-00-00",
    support_amount: "150",
    University_id_des: 1,
    organization_id: null,
    user_id: null,
    train_aria: null,
    days_of_work: "Sun,Tue",
    weekly_hours: 40,
    daily_hours: 8,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "null",
    transfer_text: "null",
    status: 0,
    inst_address: "Izbat Salman",
    inst_fax: "0945704354",
    inst_phone: "0594360110",
    trainer_name: "Trainer Name",
    train_length: 14,
    inst_name: "Foothill Technology Solutions",
    place_of_work: "",
    receive_date: "2023-01-18"
  },
  {
    id: 217,
    offer_date: "2023-01-16",
    university_id_src: 1152,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "Remote",
    train_start_date: "2023-02-01",
    train_end_date: "2023-06-01",
    support_amount: "1500",
    University_id_des: 1,
    organization_id: null,
    user_id: null,
    train_aria: "Computer Software",
    days_of_work: "Sun",
    weekly_hours: 45,
    daily_hours: 6,
    college_name: "College Name",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "null",
    residence_text: "Egypt, Giza",
    transfer_text: "Eng. Tamer Naana",
    status: 1,
    inst_address: "Foothill Technology Solutions",
    inst_fax: "0945704354",
    inst_phone: "0594360110",
    trainer_name: "Eng. Tamer Naana",
    train_length: 5,
    inst_name: "On-Site",
    place_of_work: "",
    receive_date: "2023-01-19"
  },
  {
    id: 218,
    offer_date: "2023-01-16",
    university_id_src: 1152,
    other_requirments: "GPA > 85 | 3.0",
    train_description: "Training Description anything you want to add",
    train_type: "Remote",
    train_start_date: "2024-01-01",
    train_end_date: "2025-01-01",
    support_amount: "1500",
    University_id_des: 1,
    organization_id: null,
    user_id: null,
    train_aria: "Computer Software",
    days_of_work: "Sun",
    weekly_hours: 30,
    daily_hours: 7,
    college_name: "Engineering and Technology",
    branch_name: "Computer Systems",
    major_name: "Software Engineering",
    stu_level: "Starter",
    stu_sex: "Male",
    work_field: "null",
    meals_text: "501 more to 2",
    residence_text: "2transports",
    transfer_text: "Eng. Tamer Naana",
    status: 0,
    inst_address: "Foothill Technology Solutions",
    inst_fax: "0945704354",
    inst_phone: "0594360110",
    trainer_name: "Eng. Tamer Naana",
    train_length: 16,
    inst_name: "Remote",
    place_of_work: "",
    receive_date: "2023-01-17"
  }
]

mock.onGet("/api/showOffers").reply((config) => {
  const university_id = config.params.id
  const filteredData = data.filter(
    (offer) => offer.university_id_src === university_id
  )
  return [200, filteredData]
})

mock.onPost("/api/insert_offer").reply((config) => {
  console.log({ config })
})

mock.onGet("/api/get-offer").reply((config) => {
  const offerID = config.params.id
  const offer = data.find((offer) => offer.id === offerID)
  return [200, offer]
})
